/**
AULA 1 - CONSTRUINDO E-MAIL COM HTML

VAMOS CONTRUIR UM E-MAIL MARKETING QUE ESTÃO DISPONIVEIS NO FIGMA
https://www.figma.com/file/VBwg0UUVnTzwtiriXzX0RA/Emails?node-id=0-1&t=inMrNxwYXwE1btOW-0

CADA SERVIÇO DE E-MAIL TEM UMA MANEIRA DE CONFIGURAR O E-MAIL, COMO GMAIL, HOTMAIL, ETC.

QUANDO UTILIZAMOS O HTML E CSS PARA CONSTRUIR E-MAILS USAMOS IMAGENS, PARA QUE TENHAMOS UMA APARENCIA PARECIDA TEMOS QUE USAR IMAGEN E USAR TABELAS, E CRIAR O CSS INLINE NO HTML

VAMOS CRIAR email1.html

PODEMOS ENTRAR NOS DOCUMENTOS DO FIGMA E BAIXAR OS ARQUIVOS COMO IMAGENS, COMO A CONSTRUÇÃO DE E-MAILS COM HTML UTILIZANDO TABELAS É BEM LIMITADO TEMOS QUE REALIZAR ESSE PROCEDIMENTO
> NO FIGMA SELECIONAMOS O ELEMENTO E VAMOS EM EXPORT, NO MENU LATERAL DA DIREITA, BAIXAMOS O ARQUIVO E INCLUIMOS NO HTML

AULA 2 

PARA FAZER O TESTE DOS E-MAILS VAMOS UTILIZAR UMA FERRAMENTA www.putsmail.com, VAMOS EM NEW TEST

FAZENDO O TESTE TEMOS UM ERRO NAS IMAGENS, PORTANTO TEMOS QUE CRIAR UM PROJETO NO GITHUB PARA SER UM SERVIDOR DESSAS IMAGENS, INCLUIMOS AS IMAGENS PELO PROPRIO SITE DO GITHUB, DEPOIS VAMOS NA VERCEL, FAZER DEPLOY, DEU UM ERRO POIS NÃO TEMOS O INDEX.HTML NO NOSSO REPOSITÓRIO, MAS DE QQ FORMA AS IMAGENS FUNCIOMAM ATRAVES DO ENDEREÇO:
https://servidor-estaticos-gold.vercel.app/facebook.png

TEMOS QUE SUBSTITUIR NO NOSSO HTML



 */
