/**
 AULA 1 - CARDS
 NO SITE DO BOOTSTRAP TEMOS OUTRO JEITO DE INCLUIR O ARQUIVO, NÃO VAMOS CRIAR UM LINK NO HEAD DE CSS, COPIAMOS O ENDEREÇO DA URL QUE CONTA NO CDN DO BOOTSTRAP E JOGAR NA BARRA DO NAVAGADOR, CLICAR COM O BOTÃO DIREITO E SALVAR DENTRO DA PASTA DO PROJETO EM UMA SUBPASTA CHAMADA lib, FAZER ESSE PROCESSO PARA O ARQUIVO DO CSS E JS

FORA DESSA PASTA VAMOS CRIAR UM ARQUIVO HTML, E LINKAR OS ARQUIVOS
 */
