/**
AULA 1 - ESPECIFICIDADE CSS
POSSUIMOS NO CSS 3 NIVEIS DE ESPECIFICIDADES, SEGUI DA MAIS FORTE PARA A MAIS FRACA

1) CSS INLINE > NA LINHA DO HTML
2) IDS E CLASSES > ATRAVES DA TAG STYLE OU DE UM ARQUIVO CSS
3) TAGS > STYLES QUE SERAM APLICADOS UTILIZANDO A TAG


COLOCANDO O MOUSE SOBRE A REGRA TEMOS O SELECTOR SPECIFICITY, MAS PODEMOS MUDAR ESSA REGRA COLOCANDO O SEGUINTE COMANDO !important, APÓS O VALOR DE ESTILO DO CSS

COMO FUNCIONA O CAMINHO DE UMA SELETOR:
EX: footer li  a >>> O NAVEGADOR VAI FILTAR OS a DEPOIS VAI PARA OS li QUE CONTEM UM a E DEPOIS VAI PARA OS li a QUE ESTÃO NO FOOTER

AULA 2 - INTRODUÇÃO AO SMACSS

FORNECE ALGUMAS REGRAS PARA SEGUIR NO CSS, A PROPOSTA É DIVIDIR O CODIGO CSS EM 5 CATEGORIAS:

BASE> REGRAS DE PADRÃO, USAMOS APENAS TAGS

LAYOUT> BASE DAS ESTRUTURAS, ONDE DIVIDIMOS A PAGINA EM SESSÕES

AULA 3 - INTRODUÇÃO BEM

BEM> BLOCK ELEMENT MODIFIER

EXEMPLO
BLOCK > MENU
ELEMENT > .menu-link
MODIFIER > .menu-link-active 
 */
