//ATRAVES DO JS PODEMOS RECUPERAR ATRIBUTOS DOS ELEMENTOS E PODEMOS SETAR SEUS VALORES
let nomeBeneficiario = document.getElementById("nome-beneficiario");
console.log(nomeBeneficiario);

//PARA OS inputs TEMOS UM ATRIBUTO CHAMADO .value
console.log(nomeBeneficiario.value);
//AQUI RETORNOU UM VALOR VAZIO, MAS COM ELE ATRIBUTO PODEMOS INFORMAR UM VALOR, PORTANTO É UM ATRIBUTO QUE RETORNA UM VALOR OOU DEPOMOS ATRIBUIR UM VALOR, TANTO PARA LEITURA DE UM VALOR COMO PARA A ESCRITA DE UM VALOR
//PARA ESCREVER UM VALOR EM UM CAMPO
nomeBeneficiario.value = "Gian Souza";
//NESTE COMANDO ACIMA FIZEMOS A FUNÇÃO DE UM USUARIO E ATRIBUIMOS UM VALOR
//SE COLOCARMOS nomeBeneficiario. TEREMOS ACESSO A OUTROS ATRIBUTOS QUE PODEM SER USADOS EM UM ELEMENTO DO TIPO input
//RETORNAR O type DO ELEMENTO DEFINIDO NO HTML
console.log(nomeBeneficiario.type);
//RETORNAR O id
console.log(nomeBeneficiario.id);
//SE O CAMPO É OBRIGATÓRIO
console.log(nomeBeneficiario.required);
//ACESSAR O PLACEHOLDER
console.log(nomeBeneficiario.placeholder);
//PORTANTO TODOS OS ATRIBUTOS QUE DEFINIMOS NO HTML PODEMOS ACESSAR ATRAVES DO JS

//VAMOS RECUPERAR AGORA O CAMPO VALOR
let valorDeposito = document.getElementById("valor-deposito");
console.log(valorDeposito);
//NOS CAMPOS DE TIPO NUMBER TEM UM ATRIBUTO QUE VERIFICA SE O VALOR ATRIBUIDO É VALIDO, EX: valorDeposito = 'dez' VAI DAR UM ERRO, POIS ESTÁ FORA DO RANGE DE NUMBER
valorDeposito.value = 1000;

//VALIDAÇÕES CUSTOMIZADAS > DENTRO DO NOSSO HTML TEMOS O required  QUE DIZ QUE É PRECISO COMPLETAR ALGO, MAS NÃO TEMOS DENTRO DO HTML UMA OPÇÃO DE EXIGIR QUE ESSE CAMPO TENHA O NOME COMPLETO, ESTE É UM CASO DE UMA VALIDAÇÃO CUSTOMIZADA QUE PODEMOS REALIZAR COM JS
//NAS STRING TEMOS UM RECURSO ONDE PODEMOS QUEBRAR O TEXTO, PODEMOS TRANSFORMAR A STRING EM UM ARRAY E COLOCAR O SEPARADOR QUE QUEREMOS
//nomeBeneficiario.valeu.split(' ') > COLOCAMOS DENTRO DE PARENTESES O TIPO DE SEPARADOR QUE QUEREMOS, NESSE CASO FOI UM ESPAÇO SIMPLES
console.log(nomeBeneficiario.value.split(" "));
//ESSE COMANDO NOS RETONA UM ARRAY, SE MUDARMOS O VALOR DA VARIAVEL nomeBeneficiario.value = 'Gian' NOSSO RETORNO DO split  VAI SER UMA ARRAY COM UM UNICO ITEM, PORTANTO PODEMOS USAR ISSO PARA REALIZAR UMA VALIDAÇÃO E VERIFICAR SE A PESSOA DIGITOU O NUNMERO COMPLETO
nomeBeneficiario.value = "Gian";
console.log(nomeBeneficiario.value.split(" ").length);
//TEMOS O RETORNO DE 1, PORTANTO PODEMOS USAR ESSE VALOR PARA VERIFICAR
//nomeBeneficiario.valeu.split(" ").length > 3;

//PODEMOS DESABILITAR UM BUTTON COM O COMANDO .disabled
document.getElementById("btn-depositar").disabled =
  nomeBeneficiario.valeu.split(" ").length > 3;
